# Generated by Django 3.2.7 on 2022-01-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('google_scholar', models.URLField(max_length=500, null=True)),
                ('twitter', models.URLField(max_length=500, null=True)),
                ('linkedin', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='researchpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('publication', models.CharField(max_length=250, null=True)),
                ('link', models.URLField(max_length=500, null=True)),
                ('authors', models.CharField(max_length=200, null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='researchpapercontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('abstract', models.TextField(max_length=5000, null=True)),
                ('methodology', models.TextField(max_length=5000, null=True)),
                ('result', models.TextField(max_length=5000, null=True)),
                ('discussion', models.TextField(max_length=5000, null=True)),
                ('codes', models.TextField(max_length=5000, null=True)),
                ('system', models.TextField(max_length=5000, null=True)),
            ],
        ),
    ]
