# Generated by Django 3.2.7 on 2022-01-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220131_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='result_five',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='result_four',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='result_three',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='result_two',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
