# Generated by Django 3.2.7 on 2022-01-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220131_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='methodology_five',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='methodology_four',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='methodology_three',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='methodology_two',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='codes',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='discussion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='result',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='system',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
